Package code, make pip installable, and add entrypoints
Dierme/latent-gan pull request #3
Opened 2019-06-22 10:50 UTC by cthoyt

Closes #1

This is a really big PR, so very quickly it does a few things:

- Reorganizes repository to follow python community standard
- Adds setup.cfg and setup.py and update imports so it can be pip installed (+ updated README)
- Reorganizes code that lived in `if __name__ == '__main__'` to have enclosing `main()` functions
- Adds a command line interface using entrypoints (+ updated README)

I think there are still a couple things that need to be explained (such as #2) before I can attempt to reproduce any of the results described in the manuscript. Adding more explanation to the README would be greatly appreciated.

I would be happy to explain any of the changes I made in more detail, or give you some resources that I've read along the way while I was learning all of this packaging stuff.

2019-06-23 10:39 UTC, Dierme requested changes
Thank you a lot for the pull request!

A lot of good things and cleaning and introducing the setup tools. I have left a few questions. Mainly, I want a simplified .gitignore with only essentials in it and that you reverse changes that you made to the autoencoder. 

It would also be great if you can make setuptools to be aware of the environment and run system specific command. As of now it fails in Windows environment. That is not a requirement of course  and can be thought about in the future versions.

Great work overall! Let me know if you will do the changes. Have a good day!

2019-06-23 10:39 UTC, Dierme commented on .gitignore
> -.ipynb_checkpoints/
Why deleting `__pycache__` and `.ipynb_checkpoints/` ?

2019-06-23 10:39 UTC, Dierme commented on .gitignore
> +.apdisk
Why overloading .gitignore so much? 90% of that is ignored here will never appear in this type of project. Just add the most essential things to the .gitignore to keep it simple.

2019-06-23 10:39 UTC, Dierme commented on setup.cfg
> +    Topic :: Scientific/Engineering :: Bio-Informatics
Not a bioinformatics project. Delete this tag. You can put the tags like in the manuscript or just leave it like that for me to update proper tags later.

2019-06-23 10:39 UTC, Dierme commented on setup.cfg
> +    torch
Installing torch fails on Windows. Is it possible to make setuptools to be aware of the environment and run system specific installs?

2019-06-23 10:39 UTC, Dierme commented on setup.cfg
> +python_requires = >=3.5
should be 3.6

2019-06-23 10:39 UTC, Dierme commented on src/latent_gan/autoencoder/autoencoder.py
> +    return ddc.DDC(model_name=path)
I see the idea that you tried to do to make it more flexible and optimize the imports. However it is not supposed to work this way. Reverse this one for now. I will create a stub for the autoencoder to illustrate how it works later.

2019-06-23 10:39 UTC, Dierme commented on setup.cfg
> +    torch
Installing torch fails on windows. Is it possible to make setuptools aware of the environment so it runs system specific installations?

2019-06-23 10:39 UTC, Dierme commented on setup.cfg
> +    Topic :: Scientific/Engineering :: Bio-Informatics
Not a bioinformatics project, remove this tag. I will add tags from the manuscript later.

2019-06-23 10:39 UTC, Dierme commented on setup.cfg
> +python_requires = >=3.5
should be 3.6

2019-06-23 10:39 UTC, Dierme commented on src/latent_gan/autoencoder/autoencoder.py
> -    # Import model
I think a comment here is a good thing. But maybe name it _# Loading the autoencoder model_ ?

2019-06-23 10:39 UTC, Dierme commented on src/latent_gan/decode.py
> +    model = autoencoder.load_model_from_path(model_path)
Same here for the function signature and _load_model_from_path_ - nice idea, I will use something like this, but let me insert the stub of the autoencoder first. So, reverse those two changes for now please.

2019-06-23 10:39 UTC, Dierme commented on src/latent_gan/decode_paraller.py
> +    model = autoencoder.load_model_from_path(model_path)
same as above

2019-06-23 10:39 UTC, Dierme commented on src/latent_gan/encode.py
> +    model = autoencoder.load_model_from_path(model_path)
same

2019-06-23 10:39 UTC, Dierme commented on src/latent_gan/sample.py
> +
Nice catch here! Indeed, when comparing booleans _is_ works faster.

2019-06-24 14:32 UTC, cthoyt commented on .gitignore
> -.ipynb_checkpoints/
They just got moved, but this is superseded by your request to keep it minimal. Will fix in a minute!

2019-06-24 14:35 UTC, cthoyt commented on setup.cfg
> +    torch
I think PyTorch has some complicated instructions for installing on Windows. As the Python community moves towards declarative setups (like this one) there is less room to do checking for that sort of stuff. I think the best solution would be to add something to the README for windows users to install PyTorch with something like Anaconda first.

2019-06-24 14:38 UTC, cthoyt commented on setup.cfg
> +    torch
Updated with 582f6f0

2019-06-24 14:43 UTC, cthoyt commented on src/latent_gan/autoencoder/autoencoder.py
> -    # Import model
That's a good point, maybe as a docstring would be better.

2019-06-24 14:44 UTC, cthoyt commented on src/latent_gan/decode.py
> +    model = autoencoder.load_model_from_path(model_path)
Okay, I'm sorry I made some assumptions about how this works. I'm looking forwards to seeing your example! For now, I've reverted this code to look the same as before (except I moved around where the imports were just so I didn't get any `NameError`s.)

2019-06-24 14:46 UTC, cthoyt commented
Hi @Dierme I think I've addressed all of your changes. In its current state, this PR makes the repository installable and accomplishes my original goals. The next thing I'm looking forwards to is your example autoencoder so I can try actually running the code myself!

2023-09-30 21:18 UTC, closed without merging